/* Auto-generated by genmsg_cpp for file /home/james/ros/art/utexas-art-ros-pkg-read-only/stacks/art_vehicle/art_msgs/msg/Behavior.msg */
#ifndef ART_MSGS_MESSAGE_BEHAVIOR_H
#define ART_MSGS_MESSAGE_BEHAVIOR_H
#include <string>
#include <vector>
#include <map>
#include <ostream>
#include "ros/serialization.h"
#include "ros/builtin_message_traits.h"
#include "ros/message_operations.h"
#include "ros/time.h"

#include "ros/macros.h"

#include "ros/assert.h"


namespace art_msgs
{
template <class ContainerAllocator>
struct Behavior_ {
  typedef Behavior_<ContainerAllocator> Type;

  Behavior_()
  : value(0)
  {
  }

  Behavior_(const ContainerAllocator& _alloc)
  : value(0)
  {
  }

  typedef int16_t _value_type;
  int16_t value;

  enum { Abort = 0 };
  enum { Quit = 1 };
  enum { Pause = 2 };
  enum { Run = 3 };
  enum { Suspend = 4 };
  enum { Initialize = 5 };
  enum { Go = 6 };
  enum { NONE = 7 };
  enum { N_behaviors = 8 };

private:
  static const char* __s_getDataType_() { return "art_msgs/Behavior"; }
public:
  ROS_DEPRECATED static const std::string __s_getDataType() { return __s_getDataType_(); }

  ROS_DEPRECATED const std::string __getDataType() const { return __s_getDataType_(); }

private:
  static const char* __s_getMD5Sum_() { return "88d96e38b2c952605ef152e7b2cc38ab"; }
public:
  ROS_DEPRECATED static const std::string __s_getMD5Sum() { return __s_getMD5Sum_(); }

  ROS_DEPRECATED const std::string __getMD5Sum() const { return __s_getMD5Sum_(); }

private:
  static const char* __s_getMessageDefinition_() { return "# ART Navigator behaviors (lower numbers have higher priority)\n\
# $Id$\n\
\n\
# enumerated behavior values\n\
int16 Abort       = 0\n\
int16 Quit        = 1\n\
int16 Pause       = 2\n\
int16 Run         = 3\n\
int16 Suspend     = 4\n\
int16 Initialize  = 5\n\
int16 Go          = 6\n\
int16 NONE        = 7\n\
int16 N_behaviors = 8\n\
\n\
int16 value\n\
\n\
"; }
public:
  ROS_DEPRECATED static const std::string __s_getMessageDefinition() { return __s_getMessageDefinition_(); }

  ROS_DEPRECATED const std::string __getMessageDefinition() const { return __s_getMessageDefinition_(); }

  ROS_DEPRECATED virtual uint8_t *serialize(uint8_t *write_ptr, uint32_t seq) const
  {
    ros::serialization::OStream stream(write_ptr, 1000000000);
    ros::serialization::serialize(stream, value);
    return stream.getData();
  }

  ROS_DEPRECATED virtual uint8_t *deserialize(uint8_t *read_ptr)
  {
    ros::serialization::IStream stream(read_ptr, 1000000000);
    ros::serialization::deserialize(stream, value);
    return stream.getData();
  }

  ROS_DEPRECATED virtual uint32_t serializationLength() const
  {
    uint32_t size = 0;
    size += ros::serialization::serializationLength(value);
    return size;
  }

  typedef boost::shared_ptr< ::art_msgs::Behavior_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::art_msgs::Behavior_<ContainerAllocator>  const> ConstPtr;
  boost::shared_ptr<std::map<std::string, std::string> > __connection_header;
}; // struct Behavior
typedef  ::art_msgs::Behavior_<std::allocator<void> > Behavior;

typedef boost::shared_ptr< ::art_msgs::Behavior> BehaviorPtr;
typedef boost::shared_ptr< ::art_msgs::Behavior const> BehaviorConstPtr;


template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const  ::art_msgs::Behavior_<ContainerAllocator> & v)
{
  ros::message_operations::Printer< ::art_msgs::Behavior_<ContainerAllocator> >::stream(s, "", v);
  return s;}

} // namespace art_msgs

namespace ros
{
namespace message_traits
{
template<class ContainerAllocator> struct IsMessage< ::art_msgs::Behavior_<ContainerAllocator> > : public TrueType {};
template<class ContainerAllocator> struct IsMessage< ::art_msgs::Behavior_<ContainerAllocator>  const> : public TrueType {};
template<class ContainerAllocator>
struct MD5Sum< ::art_msgs::Behavior_<ContainerAllocator> > {
  static const char* value() 
  {
    return "88d96e38b2c952605ef152e7b2cc38ab";
  }

  static const char* value(const  ::art_msgs::Behavior_<ContainerAllocator> &) { return value(); } 
  static const uint64_t static_value1 = 0x88d96e38b2c95260ULL;
  static const uint64_t static_value2 = 0x5ef152e7b2cc38abULL;
};

template<class ContainerAllocator>
struct DataType< ::art_msgs::Behavior_<ContainerAllocator> > {
  static const char* value() 
  {
    return "art_msgs/Behavior";
  }

  static const char* value(const  ::art_msgs::Behavior_<ContainerAllocator> &) { return value(); } 
};

template<class ContainerAllocator>
struct Definition< ::art_msgs::Behavior_<ContainerAllocator> > {
  static const char* value() 
  {
    return "# ART Navigator behaviors (lower numbers have higher priority)\n\
# $Id$\n\
\n\
# enumerated behavior values\n\
int16 Abort       = 0\n\
int16 Quit        = 1\n\
int16 Pause       = 2\n\
int16 Run         = 3\n\
int16 Suspend     = 4\n\
int16 Initialize  = 5\n\
int16 Go          = 6\n\
int16 NONE        = 7\n\
int16 N_behaviors = 8\n\
\n\
int16 value\n\
\n\
";
  }

  static const char* value(const  ::art_msgs::Behavior_<ContainerAllocator> &) { return value(); } 
};

template<class ContainerAllocator> struct IsFixedSize< ::art_msgs::Behavior_<ContainerAllocator> > : public TrueType {};
} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

template<class ContainerAllocator> struct Serializer< ::art_msgs::Behavior_<ContainerAllocator> >
{
  template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
  {
    stream.next(m.value);
  }

  ROS_DECLARE_ALLINONE_SERIALIZER;
}; // struct Behavior_
} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::art_msgs::Behavior_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const  ::art_msgs::Behavior_<ContainerAllocator> & v) 
  {
    s << indent << "value: ";
    Printer<int16_t>::stream(s, indent + "  ", v.value);
  }
};


} // namespace message_operations
} // namespace ros

#endif // ART_MSGS_MESSAGE_BEHAVIOR_H

