/* Auto-generated by genmsg_cpp for file /home/james/ros/art/utexas-art-ros-pkg-read-only/stacks/art_vehicle/art_msgs/msg/BrakeState.msg */
#ifndef ART_MSGS_MESSAGE_BRAKESTATE_H
#define ART_MSGS_MESSAGE_BRAKESTATE_H
#include <string>
#include <vector>
#include <map>
#include <ostream>
#include "ros/serialization.h"
#include "ros/builtin_message_traits.h"
#include "ros/message_operations.h"
#include "ros/time.h"

#include "ros/macros.h"

#include "ros/assert.h"

#include "std_msgs/Header.h"

namespace art_msgs
{
template <class ContainerAllocator>
struct BrakeState_ {
  typedef BrakeState_<ContainerAllocator> Type;

  BrakeState_()
  : header()
  , position(0.0)
  , potentiometer(0.0)
  , encoder(0.0)
  , pressure(0.0)
  {
  }

  BrakeState_(const ContainerAllocator& _alloc)
  : header(_alloc)
  , position(0.0)
  , potentiometer(0.0)
  , encoder(0.0)
  , pressure(0.0)
  {
  }

  typedef  ::std_msgs::Header_<ContainerAllocator>  _header_type;
   ::std_msgs::Header_<ContainerAllocator>  header;

  typedef float _position_type;
  float position;

  typedef float _potentiometer_type;
  float potentiometer;

  typedef float _encoder_type;
  float encoder;

  typedef float _pressure_type;
  float pressure;


private:
  static const char* __s_getDataType_() { return "art_msgs/BrakeState"; }
public:
  ROS_DEPRECATED static const std::string __s_getDataType() { return __s_getDataType_(); }

  ROS_DEPRECATED const std::string __getDataType() const { return __s_getDataType_(); }

private:
  static const char* __s_getMD5Sum_() { return "a2cf66ca94ba3a72fab2bbf4fd458de0"; }
public:
  ROS_DEPRECATED static const std::string __s_getMD5Sum() { return __s_getMD5Sum_(); }

  ROS_DEPRECATED const std::string __getMD5Sum() const { return __s_getMD5Sum_(); }

private:
  static const char* __s_getMessageDefinition_() { return "# ART brake controller state message\n\
\n\
# $Id$\n\
\n\
Header  header\n\
\n\
float32 position                # fractional position\n\
float32 potentiometer           # potentiometer voltage\n\
float32 encoder                 # encoder reading\n\
float32 pressure                # pressure sensor\n\
\n\
\n\
================================================================================\n\
MSG: std_msgs/Header\n\
# Standard metadata for higher-level stamped data types.\n\
# This is generally used to communicate timestamped data \n\
# in a particular coordinate frame.\n\
# \n\
# sequence ID: consecutively increasing ID \n\
uint32 seq\n\
#Two-integer timestamp that is expressed as:\n\
# * stamp.secs: seconds (stamp_secs) since epoch\n\
# * stamp.nsecs: nanoseconds since stamp_secs\n\
# time-handling sugar is provided by the client library\n\
time stamp\n\
#Frame this data is associated with\n\
# 0: no frame\n\
# 1: global frame\n\
string frame_id\n\
\n\
"; }
public:
  ROS_DEPRECATED static const std::string __s_getMessageDefinition() { return __s_getMessageDefinition_(); }

  ROS_DEPRECATED const std::string __getMessageDefinition() const { return __s_getMessageDefinition_(); }

  ROS_DEPRECATED virtual uint8_t *serialize(uint8_t *write_ptr, uint32_t seq) const
  {
    ros::serialization::OStream stream(write_ptr, 1000000000);
    ros::serialization::serialize(stream, header);
    ros::serialization::serialize(stream, position);
    ros::serialization::serialize(stream, potentiometer);
    ros::serialization::serialize(stream, encoder);
    ros::serialization::serialize(stream, pressure);
    return stream.getData();
  }

  ROS_DEPRECATED virtual uint8_t *deserialize(uint8_t *read_ptr)
  {
    ros::serialization::IStream stream(read_ptr, 1000000000);
    ros::serialization::deserialize(stream, header);
    ros::serialization::deserialize(stream, position);
    ros::serialization::deserialize(stream, potentiometer);
    ros::serialization::deserialize(stream, encoder);
    ros::serialization::deserialize(stream, pressure);
    return stream.getData();
  }

  ROS_DEPRECATED virtual uint32_t serializationLength() const
  {
    uint32_t size = 0;
    size += ros::serialization::serializationLength(header);
    size += ros::serialization::serializationLength(position);
    size += ros::serialization::serializationLength(potentiometer);
    size += ros::serialization::serializationLength(encoder);
    size += ros::serialization::serializationLength(pressure);
    return size;
  }

  typedef boost::shared_ptr< ::art_msgs::BrakeState_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::art_msgs::BrakeState_<ContainerAllocator>  const> ConstPtr;
  boost::shared_ptr<std::map<std::string, std::string> > __connection_header;
}; // struct BrakeState
typedef  ::art_msgs::BrakeState_<std::allocator<void> > BrakeState;

typedef boost::shared_ptr< ::art_msgs::BrakeState> BrakeStatePtr;
typedef boost::shared_ptr< ::art_msgs::BrakeState const> BrakeStateConstPtr;


template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const  ::art_msgs::BrakeState_<ContainerAllocator> & v)
{
  ros::message_operations::Printer< ::art_msgs::BrakeState_<ContainerAllocator> >::stream(s, "", v);
  return s;}

} // namespace art_msgs

namespace ros
{
namespace message_traits
{
template<class ContainerAllocator> struct IsMessage< ::art_msgs::BrakeState_<ContainerAllocator> > : public TrueType {};
template<class ContainerAllocator> struct IsMessage< ::art_msgs::BrakeState_<ContainerAllocator>  const> : public TrueType {};
template<class ContainerAllocator>
struct MD5Sum< ::art_msgs::BrakeState_<ContainerAllocator> > {
  static const char* value() 
  {
    return "a2cf66ca94ba3a72fab2bbf4fd458de0";
  }

  static const char* value(const  ::art_msgs::BrakeState_<ContainerAllocator> &) { return value(); } 
  static const uint64_t static_value1 = 0xa2cf66ca94ba3a72ULL;
  static const uint64_t static_value2 = 0xfab2bbf4fd458de0ULL;
};

template<class ContainerAllocator>
struct DataType< ::art_msgs::BrakeState_<ContainerAllocator> > {
  static const char* value() 
  {
    return "art_msgs/BrakeState";
  }

  static const char* value(const  ::art_msgs::BrakeState_<ContainerAllocator> &) { return value(); } 
};

template<class ContainerAllocator>
struct Definition< ::art_msgs::BrakeState_<ContainerAllocator> > {
  static const char* value() 
  {
    return "# ART brake controller state message\n\
\n\
# $Id$\n\
\n\
Header  header\n\
\n\
float32 position                # fractional position\n\
float32 potentiometer           # potentiometer voltage\n\
float32 encoder                 # encoder reading\n\
float32 pressure                # pressure sensor\n\
\n\
\n\
================================================================================\n\
MSG: std_msgs/Header\n\
# Standard metadata for higher-level stamped data types.\n\
# This is generally used to communicate timestamped data \n\
# in a particular coordinate frame.\n\
# \n\
# sequence ID: consecutively increasing ID \n\
uint32 seq\n\
#Two-integer timestamp that is expressed as:\n\
# * stamp.secs: seconds (stamp_secs) since epoch\n\
# * stamp.nsecs: nanoseconds since stamp_secs\n\
# time-handling sugar is provided by the client library\n\
time stamp\n\
#Frame this data is associated with\n\
# 0: no frame\n\
# 1: global frame\n\
string frame_id\n\
\n\
";
  }

  static const char* value(const  ::art_msgs::BrakeState_<ContainerAllocator> &) { return value(); } 
};

template<class ContainerAllocator> struct HasHeader< ::art_msgs::BrakeState_<ContainerAllocator> > : public TrueType {};
template<class ContainerAllocator> struct HasHeader< const ::art_msgs::BrakeState_<ContainerAllocator> > : public TrueType {};
} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

template<class ContainerAllocator> struct Serializer< ::art_msgs::BrakeState_<ContainerAllocator> >
{
  template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
  {
    stream.next(m.header);
    stream.next(m.position);
    stream.next(m.potentiometer);
    stream.next(m.encoder);
    stream.next(m.pressure);
  }

  ROS_DECLARE_ALLINONE_SERIALIZER;
}; // struct BrakeState_
} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::art_msgs::BrakeState_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const  ::art_msgs::BrakeState_<ContainerAllocator> & v) 
  {
    s << indent << "header: ";
s << std::endl;
    Printer< ::std_msgs::Header_<ContainerAllocator> >::stream(s, indent + "  ", v.header);
    s << indent << "position: ";
    Printer<float>::stream(s, indent + "  ", v.position);
    s << indent << "potentiometer: ";
    Printer<float>::stream(s, indent + "  ", v.potentiometer);
    s << indent << "encoder: ";
    Printer<float>::stream(s, indent + "  ", v.encoder);
    s << indent << "pressure: ";
    Printer<float>::stream(s, indent + "  ", v.pressure);
  }
};


} // namespace message_operations
} // namespace ros

#endif // ART_MSGS_MESSAGE_BRAKESTATE_H

