/* Auto-generated by genmsg_cpp for file /home/james/ros/art/utexas-art-ros-pkg-read-only/stacks/art_vehicle/art_msgs/msg/CarControl.msg */
#ifndef ART_MSGS_MESSAGE_CARCONTROL_H
#define ART_MSGS_MESSAGE_CARCONTROL_H
#include <string>
#include <vector>
#include <map>
#include <ostream>
#include "ros/serialization.h"
#include "ros/builtin_message_traits.h"
#include "ros/message_operations.h"
#include "ros/time.h"

#include "ros/macros.h"

#include "ros/assert.h"


namespace art_msgs
{
template <class ContainerAllocator>
struct CarControl_ {
  typedef CarControl_<ContainerAllocator> Type;

  CarControl_()
  : velocity(0.0)
  , angle(0.0)
  {
  }

  CarControl_(const ContainerAllocator& _alloc)
  : velocity(0.0)
  , angle(0.0)
  {
  }

  typedef float _velocity_type;
  float velocity;

  typedef float _angle_type;
  float angle;


private:
  static const char* __s_getDataType_() { return "art_msgs/CarControl"; }
public:
  ROS_DEPRECATED static const std::string __s_getDataType() { return __s_getDataType_(); }

  ROS_DEPRECATED const std::string __getDataType() const { return __s_getDataType_(); }

private:
  static const char* __s_getMD5Sum_() { return "23ee9ebc4f65684302501539608c3833"; }
public:
  ROS_DEPRECATED static const std::string __s_getMD5Sum() { return __s_getMD5Sum_(); }

  ROS_DEPRECATED const std::string __getMD5Sum() const { return __s_getMD5Sum_(); }

private:
  static const char* __s_getMessageDefinition_() { return "# car control command\n\
# $Id$\n\
\n\
float32 velocity                # forward velocity (m/s), negative is reverse\n\
float32 angle                   # steering angle (degrees)\n\
\n\
"; }
public:
  ROS_DEPRECATED static const std::string __s_getMessageDefinition() { return __s_getMessageDefinition_(); }

  ROS_DEPRECATED const std::string __getMessageDefinition() const { return __s_getMessageDefinition_(); }

  ROS_DEPRECATED virtual uint8_t *serialize(uint8_t *write_ptr, uint32_t seq) const
  {
    ros::serialization::OStream stream(write_ptr, 1000000000);
    ros::serialization::serialize(stream, velocity);
    ros::serialization::serialize(stream, angle);
    return stream.getData();
  }

  ROS_DEPRECATED virtual uint8_t *deserialize(uint8_t *read_ptr)
  {
    ros::serialization::IStream stream(read_ptr, 1000000000);
    ros::serialization::deserialize(stream, velocity);
    ros::serialization::deserialize(stream, angle);
    return stream.getData();
  }

  ROS_DEPRECATED virtual uint32_t serializationLength() const
  {
    uint32_t size = 0;
    size += ros::serialization::serializationLength(velocity);
    size += ros::serialization::serializationLength(angle);
    return size;
  }

  typedef boost::shared_ptr< ::art_msgs::CarControl_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::art_msgs::CarControl_<ContainerAllocator>  const> ConstPtr;
  boost::shared_ptr<std::map<std::string, std::string> > __connection_header;
}; // struct CarControl
typedef  ::art_msgs::CarControl_<std::allocator<void> > CarControl;

typedef boost::shared_ptr< ::art_msgs::CarControl> CarControlPtr;
typedef boost::shared_ptr< ::art_msgs::CarControl const> CarControlConstPtr;


template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const  ::art_msgs::CarControl_<ContainerAllocator> & v)
{
  ros::message_operations::Printer< ::art_msgs::CarControl_<ContainerAllocator> >::stream(s, "", v);
  return s;}

} // namespace art_msgs

namespace ros
{
namespace message_traits
{
template<class ContainerAllocator> struct IsMessage< ::art_msgs::CarControl_<ContainerAllocator> > : public TrueType {};
template<class ContainerAllocator> struct IsMessage< ::art_msgs::CarControl_<ContainerAllocator>  const> : public TrueType {};
template<class ContainerAllocator>
struct MD5Sum< ::art_msgs::CarControl_<ContainerAllocator> > {
  static const char* value() 
  {
    return "23ee9ebc4f65684302501539608c3833";
  }

  static const char* value(const  ::art_msgs::CarControl_<ContainerAllocator> &) { return value(); } 
  static const uint64_t static_value1 = 0x23ee9ebc4f656843ULL;
  static const uint64_t static_value2 = 0x02501539608c3833ULL;
};

template<class ContainerAllocator>
struct DataType< ::art_msgs::CarControl_<ContainerAllocator> > {
  static const char* value() 
  {
    return "art_msgs/CarControl";
  }

  static const char* value(const  ::art_msgs::CarControl_<ContainerAllocator> &) { return value(); } 
};

template<class ContainerAllocator>
struct Definition< ::art_msgs::CarControl_<ContainerAllocator> > {
  static const char* value() 
  {
    return "# car control command\n\
# $Id$\n\
\n\
float32 velocity                # forward velocity (m/s), negative is reverse\n\
float32 angle                   # steering angle (degrees)\n\
\n\
";
  }

  static const char* value(const  ::art_msgs::CarControl_<ContainerAllocator> &) { return value(); } 
};

template<class ContainerAllocator> struct IsFixedSize< ::art_msgs::CarControl_<ContainerAllocator> > : public TrueType {};
} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

template<class ContainerAllocator> struct Serializer< ::art_msgs::CarControl_<ContainerAllocator> >
{
  template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
  {
    stream.next(m.velocity);
    stream.next(m.angle);
  }

  ROS_DECLARE_ALLINONE_SERIALIZER;
}; // struct CarControl_
} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::art_msgs::CarControl_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const  ::art_msgs::CarControl_<ContainerAllocator> & v) 
  {
    s << indent << "velocity: ";
    Printer<float>::stream(s, indent + "  ", v.velocity);
    s << indent << "angle: ";
    Printer<float>::stream(s, indent + "  ", v.angle);
  }
};


} // namespace message_operations
} // namespace ros

#endif // ART_MSGS_MESSAGE_CARCONTROL_H

