/* Auto-generated by genmsg_cpp for file /home/james/ros/art/utexas-art-ros-pkg-read-only/stacks/art_vehicle/art_msgs/msg/EstopState.msg */
#ifndef ART_MSGS_MESSAGE_ESTOPSTATE_H
#define ART_MSGS_MESSAGE_ESTOPSTATE_H
#include <string>
#include <vector>
#include <map>
#include <ostream>
#include "ros/serialization.h"
#include "ros/builtin_message_traits.h"
#include "ros/message_operations.h"
#include "ros/time.h"

#include "ros/macros.h"

#include "ros/assert.h"


namespace art_msgs
{
template <class ContainerAllocator>
struct EstopState_ {
  typedef EstopState_<ContainerAllocator> Type;

  EstopState_()
  : state(0)
  {
  }

  EstopState_(const ContainerAllocator& _alloc)
  : state(0)
  {
  }

  typedef uint16_t _state_type;
  uint16_t state;

  enum { Pause = 0 };
  enum { Run = 1 };
  enum { Done = 2 };
  enum { Suspend = 3 };
  enum { N_states = 4 };

private:
  static const char* __s_getDataType_() { return "art_msgs/EstopState"; }
public:
  ROS_DEPRECATED static const std::string __s_getDataType() { return __s_getDataType_(); }

  ROS_DEPRECATED const std::string __getDataType() const { return __s_getDataType_(); }

private:
  static const char* __s_getMD5Sum_() { return "195d9329d308e6ca2b9145be58b92e7e"; }
public:
  ROS_DEPRECATED static const std::string __s_getMD5Sum() { return __s_getMD5Sum_(); }

  ROS_DEPRECATED const std::string __getMD5Sum() const { return __s_getMD5Sum_(); }

private:
  static const char* __s_getMessageDefinition_() { return "# Navigator E-stop state values\n\
# $Id$\n\
\n\
uint16 Pause    = 0			# E-stop pause (initial state)\n\
uint16 Run      = 1			# E-stop run enabled\n\
uint16 Done     = 2			# mission finished (disabled)\n\
uint16 Suspend  = 3			# suspend autonomous operation\n\
uint16 N_states = 4\n\
\n\
uint16 state\n\
\n\
"; }
public:
  ROS_DEPRECATED static const std::string __s_getMessageDefinition() { return __s_getMessageDefinition_(); }

  ROS_DEPRECATED const std::string __getMessageDefinition() const { return __s_getMessageDefinition_(); }

  ROS_DEPRECATED virtual uint8_t *serialize(uint8_t *write_ptr, uint32_t seq) const
  {
    ros::serialization::OStream stream(write_ptr, 1000000000);
    ros::serialization::serialize(stream, state);
    return stream.getData();
  }

  ROS_DEPRECATED virtual uint8_t *deserialize(uint8_t *read_ptr)
  {
    ros::serialization::IStream stream(read_ptr, 1000000000);
    ros::serialization::deserialize(stream, state);
    return stream.getData();
  }

  ROS_DEPRECATED virtual uint32_t serializationLength() const
  {
    uint32_t size = 0;
    size += ros::serialization::serializationLength(state);
    return size;
  }

  typedef boost::shared_ptr< ::art_msgs::EstopState_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::art_msgs::EstopState_<ContainerAllocator>  const> ConstPtr;
  boost::shared_ptr<std::map<std::string, std::string> > __connection_header;
}; // struct EstopState
typedef  ::art_msgs::EstopState_<std::allocator<void> > EstopState;

typedef boost::shared_ptr< ::art_msgs::EstopState> EstopStatePtr;
typedef boost::shared_ptr< ::art_msgs::EstopState const> EstopStateConstPtr;


template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const  ::art_msgs::EstopState_<ContainerAllocator> & v)
{
  ros::message_operations::Printer< ::art_msgs::EstopState_<ContainerAllocator> >::stream(s, "", v);
  return s;}

} // namespace art_msgs

namespace ros
{
namespace message_traits
{
template<class ContainerAllocator> struct IsMessage< ::art_msgs::EstopState_<ContainerAllocator> > : public TrueType {};
template<class ContainerAllocator> struct IsMessage< ::art_msgs::EstopState_<ContainerAllocator>  const> : public TrueType {};
template<class ContainerAllocator>
struct MD5Sum< ::art_msgs::EstopState_<ContainerAllocator> > {
  static const char* value() 
  {
    return "195d9329d308e6ca2b9145be58b92e7e";
  }

  static const char* value(const  ::art_msgs::EstopState_<ContainerAllocator> &) { return value(); } 
  static const uint64_t static_value1 = 0x195d9329d308e6caULL;
  static const uint64_t static_value2 = 0x2b9145be58b92e7eULL;
};

template<class ContainerAllocator>
struct DataType< ::art_msgs::EstopState_<ContainerAllocator> > {
  static const char* value() 
  {
    return "art_msgs/EstopState";
  }

  static const char* value(const  ::art_msgs::EstopState_<ContainerAllocator> &) { return value(); } 
};

template<class ContainerAllocator>
struct Definition< ::art_msgs::EstopState_<ContainerAllocator> > {
  static const char* value() 
  {
    return "# Navigator E-stop state values\n\
# $Id$\n\
\n\
uint16 Pause    = 0			# E-stop pause (initial state)\n\
uint16 Run      = 1			# E-stop run enabled\n\
uint16 Done     = 2			# mission finished (disabled)\n\
uint16 Suspend  = 3			# suspend autonomous operation\n\
uint16 N_states = 4\n\
\n\
uint16 state\n\
\n\
";
  }

  static const char* value(const  ::art_msgs::EstopState_<ContainerAllocator> &) { return value(); } 
};

template<class ContainerAllocator> struct IsFixedSize< ::art_msgs::EstopState_<ContainerAllocator> > : public TrueType {};
} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

template<class ContainerAllocator> struct Serializer< ::art_msgs::EstopState_<ContainerAllocator> >
{
  template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
  {
    stream.next(m.state);
  }

  ROS_DECLARE_ALLINONE_SERIALIZER;
}; // struct EstopState_
} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::art_msgs::EstopState_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const  ::art_msgs::EstopState_<ContainerAllocator> & v) 
  {
    s << indent << "state: ";
    Printer<uint16_t>::stream(s, indent + "  ", v.state);
  }
};


} // namespace message_operations
} // namespace ros

#endif // ART_MSGS_MESSAGE_ESTOPSTATE_H

