/* Auto-generated by genmsg_cpp for file /home/james/ros/art/utexas-art-ros-pkg-read-only/stacks/art_vehicle/art_msgs/msg/IOadrCommand.msg */
#ifndef ART_MSGS_MESSAGE_IOADRCOMMAND_H
#define ART_MSGS_MESSAGE_IOADRCOMMAND_H
#include <string>
#include <vector>
#include <map>
#include <ostream>
#include "ros/serialization.h"
#include "ros/builtin_message_traits.h"
#include "ros/message_operations.h"
#include "ros/time.h"

#include "ros/macros.h"

#include "ros/assert.h"

#include "std_msgs/Header.h"

namespace art_msgs
{
template <class ContainerAllocator>
struct IOadrCommand_ {
  typedef IOadrCommand_<ContainerAllocator> Type;

  IOadrCommand_()
  : header()
  , relays_on(0)
  , relays_off(0)
  {
  }

  IOadrCommand_(const ContainerAllocator& _alloc)
  : header(_alloc)
  , relays_on(0)
  , relays_off(0)
  {
  }

  typedef  ::std_msgs::Header_<ContainerAllocator>  _header_type;
   ::std_msgs::Header_<ContainerAllocator>  header;

  typedef uint8_t _relays_on_type;
  uint8_t relays_on;

  typedef uint8_t _relays_off_type;
  uint8_t relays_off;


private:
  static const char* __s_getDataType_() { return "art_msgs/IOadrCommand"; }
public:
  ROS_DEPRECATED static const std::string __s_getDataType() { return __s_getDataType_(); }

  ROS_DEPRECATED const std::string __getDataType() const { return __s_getDataType_(); }

private:
  static const char* __s_getMD5Sum_() { return "1ba0a21767ee8a4bb7c80945f20b670c"; }
public:
  ROS_DEPRECATED static const std::string __s_getMD5Sum() { return __s_getMD5Sum_(); }

  ROS_DEPRECATED const std::string __getMD5Sum() const { return __s_getMD5Sum_(); }

private:
  static const char* __s_getMessageDefinition_() { return "# NCD IOADR8x controller command message for ART vehicle\n\
#\n\
# Sets or clears relays.  See: IOadrState for bit definitions.\n\
\n\
# $Id$\n\
\n\
Header  header          # standard ROS message header\n\
\n\
uint8 relays_on         # relays to set\n\
uint8 relays_off        # relays to clear\n\
\n\
================================================================================\n\
MSG: std_msgs/Header\n\
# Standard metadata for higher-level stamped data types.\n\
# This is generally used to communicate timestamped data \n\
# in a particular coordinate frame.\n\
# \n\
# sequence ID: consecutively increasing ID \n\
uint32 seq\n\
#Two-integer timestamp that is expressed as:\n\
# * stamp.secs: seconds (stamp_secs) since epoch\n\
# * stamp.nsecs: nanoseconds since stamp_secs\n\
# time-handling sugar is provided by the client library\n\
time stamp\n\
#Frame this data is associated with\n\
# 0: no frame\n\
# 1: global frame\n\
string frame_id\n\
\n\
"; }
public:
  ROS_DEPRECATED static const std::string __s_getMessageDefinition() { return __s_getMessageDefinition_(); }

  ROS_DEPRECATED const std::string __getMessageDefinition() const { return __s_getMessageDefinition_(); }

  ROS_DEPRECATED virtual uint8_t *serialize(uint8_t *write_ptr, uint32_t seq) const
  {
    ros::serialization::OStream stream(write_ptr, 1000000000);
    ros::serialization::serialize(stream, header);
    ros::serialization::serialize(stream, relays_on);
    ros::serialization::serialize(stream, relays_off);
    return stream.getData();
  }

  ROS_DEPRECATED virtual uint8_t *deserialize(uint8_t *read_ptr)
  {
    ros::serialization::IStream stream(read_ptr, 1000000000);
    ros::serialization::deserialize(stream, header);
    ros::serialization::deserialize(stream, relays_on);
    ros::serialization::deserialize(stream, relays_off);
    return stream.getData();
  }

  ROS_DEPRECATED virtual uint32_t serializationLength() const
  {
    uint32_t size = 0;
    size += ros::serialization::serializationLength(header);
    size += ros::serialization::serializationLength(relays_on);
    size += ros::serialization::serializationLength(relays_off);
    return size;
  }

  typedef boost::shared_ptr< ::art_msgs::IOadrCommand_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::art_msgs::IOadrCommand_<ContainerAllocator>  const> ConstPtr;
  boost::shared_ptr<std::map<std::string, std::string> > __connection_header;
}; // struct IOadrCommand
typedef  ::art_msgs::IOadrCommand_<std::allocator<void> > IOadrCommand;

typedef boost::shared_ptr< ::art_msgs::IOadrCommand> IOadrCommandPtr;
typedef boost::shared_ptr< ::art_msgs::IOadrCommand const> IOadrCommandConstPtr;


template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const  ::art_msgs::IOadrCommand_<ContainerAllocator> & v)
{
  ros::message_operations::Printer< ::art_msgs::IOadrCommand_<ContainerAllocator> >::stream(s, "", v);
  return s;}

} // namespace art_msgs

namespace ros
{
namespace message_traits
{
template<class ContainerAllocator> struct IsMessage< ::art_msgs::IOadrCommand_<ContainerAllocator> > : public TrueType {};
template<class ContainerAllocator> struct IsMessage< ::art_msgs::IOadrCommand_<ContainerAllocator>  const> : public TrueType {};
template<class ContainerAllocator>
struct MD5Sum< ::art_msgs::IOadrCommand_<ContainerAllocator> > {
  static const char* value() 
  {
    return "1ba0a21767ee8a4bb7c80945f20b670c";
  }

  static const char* value(const  ::art_msgs::IOadrCommand_<ContainerAllocator> &) { return value(); } 
  static const uint64_t static_value1 = 0x1ba0a21767ee8a4bULL;
  static const uint64_t static_value2 = 0xb7c80945f20b670cULL;
};

template<class ContainerAllocator>
struct DataType< ::art_msgs::IOadrCommand_<ContainerAllocator> > {
  static const char* value() 
  {
    return "art_msgs/IOadrCommand";
  }

  static const char* value(const  ::art_msgs::IOadrCommand_<ContainerAllocator> &) { return value(); } 
};

template<class ContainerAllocator>
struct Definition< ::art_msgs::IOadrCommand_<ContainerAllocator> > {
  static const char* value() 
  {
    return "# NCD IOADR8x controller command message for ART vehicle\n\
#\n\
# Sets or clears relays.  See: IOadrState for bit definitions.\n\
\n\
# $Id$\n\
\n\
Header  header          # standard ROS message header\n\
\n\
uint8 relays_on         # relays to set\n\
uint8 relays_off        # relays to clear\n\
\n\
================================================================================\n\
MSG: std_msgs/Header\n\
# Standard metadata for higher-level stamped data types.\n\
# This is generally used to communicate timestamped data \n\
# in a particular coordinate frame.\n\
# \n\
# sequence ID: consecutively increasing ID \n\
uint32 seq\n\
#Two-integer timestamp that is expressed as:\n\
# * stamp.secs: seconds (stamp_secs) since epoch\n\
# * stamp.nsecs: nanoseconds since stamp_secs\n\
# time-handling sugar is provided by the client library\n\
time stamp\n\
#Frame this data is associated with\n\
# 0: no frame\n\
# 1: global frame\n\
string frame_id\n\
\n\
";
  }

  static const char* value(const  ::art_msgs::IOadrCommand_<ContainerAllocator> &) { return value(); } 
};

template<class ContainerAllocator> struct HasHeader< ::art_msgs::IOadrCommand_<ContainerAllocator> > : public TrueType {};
template<class ContainerAllocator> struct HasHeader< const ::art_msgs::IOadrCommand_<ContainerAllocator> > : public TrueType {};
} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

template<class ContainerAllocator> struct Serializer< ::art_msgs::IOadrCommand_<ContainerAllocator> >
{
  template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
  {
    stream.next(m.header);
    stream.next(m.relays_on);
    stream.next(m.relays_off);
  }

  ROS_DECLARE_ALLINONE_SERIALIZER;
}; // struct IOadrCommand_
} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::art_msgs::IOadrCommand_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const  ::art_msgs::IOadrCommand_<ContainerAllocator> & v) 
  {
    s << indent << "header: ";
s << std::endl;
    Printer< ::std_msgs::Header_<ContainerAllocator> >::stream(s, indent + "  ", v.header);
    s << indent << "relays_on: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.relays_on);
    s << indent << "relays_off: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.relays_off);
  }
};


} // namespace message_operations
} // namespace ros

#endif // ART_MSGS_MESSAGE_IOADRCOMMAND_H

