/* Auto-generated by genmsg_cpp for file /home/james/ros/art/utexas-art-ros-pkg-read-only/stacks/art_vehicle/art_msgs/msg/LearningCommand.msg */
#ifndef ART_MSGS_MESSAGE_LEARNINGCOMMAND_H
#define ART_MSGS_MESSAGE_LEARNINGCOMMAND_H
#include <string>
#include <vector>
#include <map>
#include <ostream>
#include "ros/serialization.h"
#include "ros/builtin_message_traits.h"
#include "ros/message_operations.h"
#include "ros/time.h"

#include "ros/macros.h"

#include "ros/assert.h"

#include "std_msgs/Header.h"

namespace art_msgs
{
template <class ContainerAllocator>
struct LearningCommand_ {
  typedef LearningCommand_<ContainerAllocator> Type;

  LearningCommand_()
  : header()
  , pilotActive(0)
  {
  }

  LearningCommand_(const ContainerAllocator& _alloc)
  : header(_alloc)
  , pilotActive(0)
  {
  }

  typedef  ::std_msgs::Header_<ContainerAllocator>  _header_type;
   ::std_msgs::Header_<ContainerAllocator>  header;

  typedef int8_t _pilotActive_type;
  int8_t pilotActive;


private:
  static const char* __s_getDataType_() { return "art_msgs/LearningCommand"; }
public:
  ROS_DEPRECATED static const std::string __s_getDataType() { return __s_getDataType_(); }

  ROS_DEPRECATED const std::string __getDataType() const { return __s_getDataType_(); }

private:
  static const char* __s_getMD5Sum_() { return "ddd1e597cd0c1d6b0d1497108b462a51"; }
public:
  ROS_DEPRECATED static const std::string __s_getMD5Sum() { return __s_getMD5Sum_(); }

  ROS_DEPRECATED const std::string __getMD5Sum() const { return __s_getMD5Sum_(); }

private:
  static const char* __s_getMessageDefinition_() { return "# Lets us turn on or off different modules using a message\n\
# For example, I can disable pilot for some parts of learning\n\
\n\
# $Id$\n\
\n\
Header     header\n\
int8       pilotActive\n\
\n\
================================================================================\n\
MSG: std_msgs/Header\n\
# Standard metadata for higher-level stamped data types.\n\
# This is generally used to communicate timestamped data \n\
# in a particular coordinate frame.\n\
# \n\
# sequence ID: consecutively increasing ID \n\
uint32 seq\n\
#Two-integer timestamp that is expressed as:\n\
# * stamp.secs: seconds (stamp_secs) since epoch\n\
# * stamp.nsecs: nanoseconds since stamp_secs\n\
# time-handling sugar is provided by the client library\n\
time stamp\n\
#Frame this data is associated with\n\
# 0: no frame\n\
# 1: global frame\n\
string frame_id\n\
\n\
"; }
public:
  ROS_DEPRECATED static const std::string __s_getMessageDefinition() { return __s_getMessageDefinition_(); }

  ROS_DEPRECATED const std::string __getMessageDefinition() const { return __s_getMessageDefinition_(); }

  ROS_DEPRECATED virtual uint8_t *serialize(uint8_t *write_ptr, uint32_t seq) const
  {
    ros::serialization::OStream stream(write_ptr, 1000000000);
    ros::serialization::serialize(stream, header);
    ros::serialization::serialize(stream, pilotActive);
    return stream.getData();
  }

  ROS_DEPRECATED virtual uint8_t *deserialize(uint8_t *read_ptr)
  {
    ros::serialization::IStream stream(read_ptr, 1000000000);
    ros::serialization::deserialize(stream, header);
    ros::serialization::deserialize(stream, pilotActive);
    return stream.getData();
  }

  ROS_DEPRECATED virtual uint32_t serializationLength() const
  {
    uint32_t size = 0;
    size += ros::serialization::serializationLength(header);
    size += ros::serialization::serializationLength(pilotActive);
    return size;
  }

  typedef boost::shared_ptr< ::art_msgs::LearningCommand_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::art_msgs::LearningCommand_<ContainerAllocator>  const> ConstPtr;
  boost::shared_ptr<std::map<std::string, std::string> > __connection_header;
}; // struct LearningCommand
typedef  ::art_msgs::LearningCommand_<std::allocator<void> > LearningCommand;

typedef boost::shared_ptr< ::art_msgs::LearningCommand> LearningCommandPtr;
typedef boost::shared_ptr< ::art_msgs::LearningCommand const> LearningCommandConstPtr;


template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const  ::art_msgs::LearningCommand_<ContainerAllocator> & v)
{
  ros::message_operations::Printer< ::art_msgs::LearningCommand_<ContainerAllocator> >::stream(s, "", v);
  return s;}

} // namespace art_msgs

namespace ros
{
namespace message_traits
{
template<class ContainerAllocator> struct IsMessage< ::art_msgs::LearningCommand_<ContainerAllocator> > : public TrueType {};
template<class ContainerAllocator> struct IsMessage< ::art_msgs::LearningCommand_<ContainerAllocator>  const> : public TrueType {};
template<class ContainerAllocator>
struct MD5Sum< ::art_msgs::LearningCommand_<ContainerAllocator> > {
  static const char* value() 
  {
    return "ddd1e597cd0c1d6b0d1497108b462a51";
  }

  static const char* value(const  ::art_msgs::LearningCommand_<ContainerAllocator> &) { return value(); } 
  static const uint64_t static_value1 = 0xddd1e597cd0c1d6bULL;
  static const uint64_t static_value2 = 0x0d1497108b462a51ULL;
};

template<class ContainerAllocator>
struct DataType< ::art_msgs::LearningCommand_<ContainerAllocator> > {
  static const char* value() 
  {
    return "art_msgs/LearningCommand";
  }

  static const char* value(const  ::art_msgs::LearningCommand_<ContainerAllocator> &) { return value(); } 
};

template<class ContainerAllocator>
struct Definition< ::art_msgs::LearningCommand_<ContainerAllocator> > {
  static const char* value() 
  {
    return "# Lets us turn on or off different modules using a message\n\
# For example, I can disable pilot for some parts of learning\n\
\n\
# $Id$\n\
\n\
Header     header\n\
int8       pilotActive\n\
\n\
================================================================================\n\
MSG: std_msgs/Header\n\
# Standard metadata for higher-level stamped data types.\n\
# This is generally used to communicate timestamped data \n\
# in a particular coordinate frame.\n\
# \n\
# sequence ID: consecutively increasing ID \n\
uint32 seq\n\
#Two-integer timestamp that is expressed as:\n\
# * stamp.secs: seconds (stamp_secs) since epoch\n\
# * stamp.nsecs: nanoseconds since stamp_secs\n\
# time-handling sugar is provided by the client library\n\
time stamp\n\
#Frame this data is associated with\n\
# 0: no frame\n\
# 1: global frame\n\
string frame_id\n\
\n\
";
  }

  static const char* value(const  ::art_msgs::LearningCommand_<ContainerAllocator> &) { return value(); } 
};

template<class ContainerAllocator> struct HasHeader< ::art_msgs::LearningCommand_<ContainerAllocator> > : public TrueType {};
template<class ContainerAllocator> struct HasHeader< const ::art_msgs::LearningCommand_<ContainerAllocator> > : public TrueType {};
} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

template<class ContainerAllocator> struct Serializer< ::art_msgs::LearningCommand_<ContainerAllocator> >
{
  template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
  {
    stream.next(m.header);
    stream.next(m.pilotActive);
  }

  ROS_DECLARE_ALLINONE_SERIALIZER;
}; // struct LearningCommand_
} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::art_msgs::LearningCommand_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const  ::art_msgs::LearningCommand_<ContainerAllocator> & v) 
  {
    s << indent << "header: ";
s << std::endl;
    Printer< ::std_msgs::Header_<ContainerAllocator> >::stream(s, indent + "  ", v.header);
    s << indent << "pilotActive: ";
    Printer<int8_t>::stream(s, indent + "  ", v.pilotActive);
  }
};


} // namespace message_operations
} // namespace ros

#endif // ART_MSGS_MESSAGE_LEARNINGCOMMAND_H

