/* Auto-generated by genmsg_cpp for file /home/james/ros/art/utexas-art-ros-pkg-read-only/stacks/art_vehicle/art_msgs/msg/Shifter.msg */
#ifndef ART_MSGS_MESSAGE_SHIFTER_H
#define ART_MSGS_MESSAGE_SHIFTER_H
#include <string>
#include <vector>
#include <map>
#include <ostream>
#include "ros/serialization.h"
#include "ros/builtin_message_traits.h"
#include "ros/message_operations.h"
#include "ros/time.h"

#include "ros/macros.h"

#include "ros/assert.h"

#include "std_msgs/Header.h"

namespace art_msgs
{
template <class ContainerAllocator>
struct Shifter_ {
  typedef Shifter_<ContainerAllocator> Type;

  Shifter_()
  : header()
  , gear(0)
  , relays(0)
  {
  }

  Shifter_(const ContainerAllocator& _alloc)
  : header(_alloc)
  , gear(0)
  , relays(0)
  {
  }

  typedef  ::std_msgs::Header_<ContainerAllocator>  _header_type;
   ::std_msgs::Header_<ContainerAllocator>  header;

  typedef uint8_t _gear_type;
  uint8_t gear;

  typedef uint8_t _relays_type;
  uint8_t relays;

  enum { Reset = 0 };
  enum { Park = 1 };
  enum { Reverse = 2 };
  enum { Neutral = 3 };
  enum { Drive = 4 };

private:
  static const char* __s_getDataType_() { return "art_msgs/Shifter"; }
public:
  ROS_DEPRECATED static const std::string __s_getDataType() { return __s_getDataType_(); }

  ROS_DEPRECATED const std::string __getDataType() const { return __s_getDataType_(); }

private:
  static const char* __s_getMD5Sum_() { return "dddb61d8575e01ea7857ef1b3a7b941c"; }
public:
  ROS_DEPRECATED static const std::string __s_getMD5Sum() { return __s_getMD5Sum_(); }

  ROS_DEPRECATED const std::string __getMD5Sum() const { return __s_getMD5Sum_(); }

private:
  static const char* __s_getMessageDefinition_() { return "# ART shifter message\n\
#\n\
# Used to both request and report gear shifts.\n\
\n\
# $Id$\n\
\n\
# Our Arens Controls hardware mechanism requires holding the shift\n\
# relay on for one second before resetting it.  A command node must\n\
# request the desired gear, then wait a second before sending the\n\
# Reset command.  To be safe, it should check that the shift actually\n\
# occurred before continuing.\n\
\n\
Header  header          # standard ROS message header\n\
\n\
# gear numbers\n\
uint8 Reset = 0         # request reset of shifter relays\n\
uint8 Park = 1\n\
uint8 Reverse = 2\n\
uint8 Neutral = 3\n\
uint8 Drive = 4\n\
\n\
uint8 gear              # requested or reported gear number\n\
uint8 relays            # current relay values\n\
\n\
================================================================================\n\
MSG: std_msgs/Header\n\
# Standard metadata for higher-level stamped data types.\n\
# This is generally used to communicate timestamped data \n\
# in a particular coordinate frame.\n\
# \n\
# sequence ID: consecutively increasing ID \n\
uint32 seq\n\
#Two-integer timestamp that is expressed as:\n\
# * stamp.secs: seconds (stamp_secs) since epoch\n\
# * stamp.nsecs: nanoseconds since stamp_secs\n\
# time-handling sugar is provided by the client library\n\
time stamp\n\
#Frame this data is associated with\n\
# 0: no frame\n\
# 1: global frame\n\
string frame_id\n\
\n\
"; }
public:
  ROS_DEPRECATED static const std::string __s_getMessageDefinition() { return __s_getMessageDefinition_(); }

  ROS_DEPRECATED const std::string __getMessageDefinition() const { return __s_getMessageDefinition_(); }

  ROS_DEPRECATED virtual uint8_t *serialize(uint8_t *write_ptr, uint32_t seq) const
  {
    ros::serialization::OStream stream(write_ptr, 1000000000);
    ros::serialization::serialize(stream, header);
    ros::serialization::serialize(stream, gear);
    ros::serialization::serialize(stream, relays);
    return stream.getData();
  }

  ROS_DEPRECATED virtual uint8_t *deserialize(uint8_t *read_ptr)
  {
    ros::serialization::IStream stream(read_ptr, 1000000000);
    ros::serialization::deserialize(stream, header);
    ros::serialization::deserialize(stream, gear);
    ros::serialization::deserialize(stream, relays);
    return stream.getData();
  }

  ROS_DEPRECATED virtual uint32_t serializationLength() const
  {
    uint32_t size = 0;
    size += ros::serialization::serializationLength(header);
    size += ros::serialization::serializationLength(gear);
    size += ros::serialization::serializationLength(relays);
    return size;
  }

  typedef boost::shared_ptr< ::art_msgs::Shifter_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::art_msgs::Shifter_<ContainerAllocator>  const> ConstPtr;
  boost::shared_ptr<std::map<std::string, std::string> > __connection_header;
}; // struct Shifter
typedef  ::art_msgs::Shifter_<std::allocator<void> > Shifter;

typedef boost::shared_ptr< ::art_msgs::Shifter> ShifterPtr;
typedef boost::shared_ptr< ::art_msgs::Shifter const> ShifterConstPtr;


template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const  ::art_msgs::Shifter_<ContainerAllocator> & v)
{
  ros::message_operations::Printer< ::art_msgs::Shifter_<ContainerAllocator> >::stream(s, "", v);
  return s;}

} // namespace art_msgs

namespace ros
{
namespace message_traits
{
template<class ContainerAllocator> struct IsMessage< ::art_msgs::Shifter_<ContainerAllocator> > : public TrueType {};
template<class ContainerAllocator> struct IsMessage< ::art_msgs::Shifter_<ContainerAllocator>  const> : public TrueType {};
template<class ContainerAllocator>
struct MD5Sum< ::art_msgs::Shifter_<ContainerAllocator> > {
  static const char* value() 
  {
    return "dddb61d8575e01ea7857ef1b3a7b941c";
  }

  static const char* value(const  ::art_msgs::Shifter_<ContainerAllocator> &) { return value(); } 
  static const uint64_t static_value1 = 0xdddb61d8575e01eaULL;
  static const uint64_t static_value2 = 0x7857ef1b3a7b941cULL;
};

template<class ContainerAllocator>
struct DataType< ::art_msgs::Shifter_<ContainerAllocator> > {
  static const char* value() 
  {
    return "art_msgs/Shifter";
  }

  static const char* value(const  ::art_msgs::Shifter_<ContainerAllocator> &) { return value(); } 
};

template<class ContainerAllocator>
struct Definition< ::art_msgs::Shifter_<ContainerAllocator> > {
  static const char* value() 
  {
    return "# ART shifter message\n\
#\n\
# Used to both request and report gear shifts.\n\
\n\
# $Id$\n\
\n\
# Our Arens Controls hardware mechanism requires holding the shift\n\
# relay on for one second before resetting it.  A command node must\n\
# request the desired gear, then wait a second before sending the\n\
# Reset command.  To be safe, it should check that the shift actually\n\
# occurred before continuing.\n\
\n\
Header  header          # standard ROS message header\n\
\n\
# gear numbers\n\
uint8 Reset = 0         # request reset of shifter relays\n\
uint8 Park = 1\n\
uint8 Reverse = 2\n\
uint8 Neutral = 3\n\
uint8 Drive = 4\n\
\n\
uint8 gear              # requested or reported gear number\n\
uint8 relays            # current relay values\n\
\n\
================================================================================\n\
MSG: std_msgs/Header\n\
# Standard metadata for higher-level stamped data types.\n\
# This is generally used to communicate timestamped data \n\
# in a particular coordinate frame.\n\
# \n\
# sequence ID: consecutively increasing ID \n\
uint32 seq\n\
#Two-integer timestamp that is expressed as:\n\
# * stamp.secs: seconds (stamp_secs) since epoch\n\
# * stamp.nsecs: nanoseconds since stamp_secs\n\
# time-handling sugar is provided by the client library\n\
time stamp\n\
#Frame this data is associated with\n\
# 0: no frame\n\
# 1: global frame\n\
string frame_id\n\
\n\
";
  }

  static const char* value(const  ::art_msgs::Shifter_<ContainerAllocator> &) { return value(); } 
};

template<class ContainerAllocator> struct HasHeader< ::art_msgs::Shifter_<ContainerAllocator> > : public TrueType {};
template<class ContainerAllocator> struct HasHeader< const ::art_msgs::Shifter_<ContainerAllocator> > : public TrueType {};
} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

template<class ContainerAllocator> struct Serializer< ::art_msgs::Shifter_<ContainerAllocator> >
{
  template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
  {
    stream.next(m.header);
    stream.next(m.gear);
    stream.next(m.relays);
  }

  ROS_DECLARE_ALLINONE_SERIALIZER;
}; // struct Shifter_
} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::art_msgs::Shifter_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const  ::art_msgs::Shifter_<ContainerAllocator> & v) 
  {
    s << indent << "header: ";
s << std::endl;
    Printer< ::std_msgs::Header_<ContainerAllocator> >::stream(s, indent + "  ", v.header);
    s << indent << "gear: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.gear);
    s << indent << "relays: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.relays);
  }
};


} // namespace message_operations
} // namespace ros

#endif // ART_MSGS_MESSAGE_SHIFTER_H

