/* Auto-generated by genmsg_cpp for file /home/james/ros/art/utexas-art-ros-pkg-read-only/stacks/art_vehicle/art_msgs/msg/SteeringState.msg */
#ifndef ART_MSGS_MESSAGE_STEERINGSTATE_H
#define ART_MSGS_MESSAGE_STEERINGSTATE_H
#include <string>
#include <vector>
#include <map>
#include <ostream>
#include "ros/serialization.h"
#include "ros/builtin_message_traits.h"
#include "ros/message_operations.h"
#include "ros/time.h"

#include "ros/macros.h"

#include "ros/assert.h"

#include "std_msgs/Header.h"
#include "art_msgs/DriverState.h"

namespace art_msgs
{
template <class ContainerAllocator>
struct SteeringState_ {
  typedef SteeringState_<ContainerAllocator> Type;

  SteeringState_()
  : header()
  , driver()
  , angle(0.0)
  , sensor(0.0)
  {
  }

  SteeringState_(const ContainerAllocator& _alloc)
  : header(_alloc)
  , driver(_alloc)
  , angle(0.0)
  , sensor(0.0)
  {
  }

  typedef  ::std_msgs::Header_<ContainerAllocator>  _header_type;
   ::std_msgs::Header_<ContainerAllocator>  header;

  typedef  ::art_msgs::DriverState_<ContainerAllocator>  _driver_type;
   ::art_msgs::DriverState_<ContainerAllocator>  driver;

  typedef float _angle_type;
  float angle;

  typedef float _sensor_type;
  float sensor;


private:
  static const char* __s_getDataType_() { return "art_msgs/SteeringState"; }
public:
  ROS_DEPRECATED static const std::string __s_getDataType() { return __s_getDataType_(); }

  ROS_DEPRECATED const std::string __getDataType() const { return __s_getDataType_(); }

private:
  static const char* __s_getMD5Sum_() { return "7bf11da138f80579d285d99bea47f6d3"; }
public:
  ROS_DEPRECATED static const std::string __s_getMD5Sum() { return __s_getMD5Sum_(); }

  ROS_DEPRECATED const std::string __getMD5Sum() const { return __s_getMD5Sum_(); }

private:
  static const char* __s_getMessageDefinition_() { return "# ART steering controller state message\n\
\n\
# $Id$\n\
\n\
Header  header\n\
\n\
DriverState driver              # driver state\n\
float32 angle                   # steering angle in degrees\n\
float32 sensor                  # steering sensor voltage\n\
\n\
\n\
================================================================================\n\
MSG: std_msgs/Header\n\
# Standard metadata for higher-level stamped data types.\n\
# This is generally used to communicate timestamped data \n\
# in a particular coordinate frame.\n\
# \n\
# sequence ID: consecutively increasing ID \n\
uint32 seq\n\
#Two-integer timestamp that is expressed as:\n\
# * stamp.secs: seconds (stamp_secs) since epoch\n\
# * stamp.nsecs: nanoseconds since stamp_secs\n\
# time-handling sugar is provided by the client library\n\
time stamp\n\
#Frame this data is associated with\n\
# 0: no frame\n\
# 1: global frame\n\
string frame_id\n\
\n\
================================================================================\n\
MSG: art_msgs/DriverState\n\
# ART driver states -- similar to those in driver_base.\n\
\n\
# $Id$\n\
\n\
# constants\n\
uint32 CLOSED = 0       # Not connected to the hardware\n\
uint32 OPENED = 1       # Passively connected to the hardware\n\
uint32 RUNNING = 2      # Sending hardware commands\n\
\n\
uint32 state\n\
\n\
"; }
public:
  ROS_DEPRECATED static const std::string __s_getMessageDefinition() { return __s_getMessageDefinition_(); }

  ROS_DEPRECATED const std::string __getMessageDefinition() const { return __s_getMessageDefinition_(); }

  ROS_DEPRECATED virtual uint8_t *serialize(uint8_t *write_ptr, uint32_t seq) const
  {
    ros::serialization::OStream stream(write_ptr, 1000000000);
    ros::serialization::serialize(stream, header);
    ros::serialization::serialize(stream, driver);
    ros::serialization::serialize(stream, angle);
    ros::serialization::serialize(stream, sensor);
    return stream.getData();
  }

  ROS_DEPRECATED virtual uint8_t *deserialize(uint8_t *read_ptr)
  {
    ros::serialization::IStream stream(read_ptr, 1000000000);
    ros::serialization::deserialize(stream, header);
    ros::serialization::deserialize(stream, driver);
    ros::serialization::deserialize(stream, angle);
    ros::serialization::deserialize(stream, sensor);
    return stream.getData();
  }

  ROS_DEPRECATED virtual uint32_t serializationLength() const
  {
    uint32_t size = 0;
    size += ros::serialization::serializationLength(header);
    size += ros::serialization::serializationLength(driver);
    size += ros::serialization::serializationLength(angle);
    size += ros::serialization::serializationLength(sensor);
    return size;
  }

  typedef boost::shared_ptr< ::art_msgs::SteeringState_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::art_msgs::SteeringState_<ContainerAllocator>  const> ConstPtr;
  boost::shared_ptr<std::map<std::string, std::string> > __connection_header;
}; // struct SteeringState
typedef  ::art_msgs::SteeringState_<std::allocator<void> > SteeringState;

typedef boost::shared_ptr< ::art_msgs::SteeringState> SteeringStatePtr;
typedef boost::shared_ptr< ::art_msgs::SteeringState const> SteeringStateConstPtr;


template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const  ::art_msgs::SteeringState_<ContainerAllocator> & v)
{
  ros::message_operations::Printer< ::art_msgs::SteeringState_<ContainerAllocator> >::stream(s, "", v);
  return s;}

} // namespace art_msgs

namespace ros
{
namespace message_traits
{
template<class ContainerAllocator> struct IsMessage< ::art_msgs::SteeringState_<ContainerAllocator> > : public TrueType {};
template<class ContainerAllocator> struct IsMessage< ::art_msgs::SteeringState_<ContainerAllocator>  const> : public TrueType {};
template<class ContainerAllocator>
struct MD5Sum< ::art_msgs::SteeringState_<ContainerAllocator> > {
  static const char* value() 
  {
    return "7bf11da138f80579d285d99bea47f6d3";
  }

  static const char* value(const  ::art_msgs::SteeringState_<ContainerAllocator> &) { return value(); } 
  static const uint64_t static_value1 = 0x7bf11da138f80579ULL;
  static const uint64_t static_value2 = 0xd285d99bea47f6d3ULL;
};

template<class ContainerAllocator>
struct DataType< ::art_msgs::SteeringState_<ContainerAllocator> > {
  static const char* value() 
  {
    return "art_msgs/SteeringState";
  }

  static const char* value(const  ::art_msgs::SteeringState_<ContainerAllocator> &) { return value(); } 
};

template<class ContainerAllocator>
struct Definition< ::art_msgs::SteeringState_<ContainerAllocator> > {
  static const char* value() 
  {
    return "# ART steering controller state message\n\
\n\
# $Id$\n\
\n\
Header  header\n\
\n\
DriverState driver              # driver state\n\
float32 angle                   # steering angle in degrees\n\
float32 sensor                  # steering sensor voltage\n\
\n\
\n\
================================================================================\n\
MSG: std_msgs/Header\n\
# Standard metadata for higher-level stamped data types.\n\
# This is generally used to communicate timestamped data \n\
# in a particular coordinate frame.\n\
# \n\
# sequence ID: consecutively increasing ID \n\
uint32 seq\n\
#Two-integer timestamp that is expressed as:\n\
# * stamp.secs: seconds (stamp_secs) since epoch\n\
# * stamp.nsecs: nanoseconds since stamp_secs\n\
# time-handling sugar is provided by the client library\n\
time stamp\n\
#Frame this data is associated with\n\
# 0: no frame\n\
# 1: global frame\n\
string frame_id\n\
\n\
================================================================================\n\
MSG: art_msgs/DriverState\n\
# ART driver states -- similar to those in driver_base.\n\
\n\
# $Id$\n\
\n\
# constants\n\
uint32 CLOSED = 0       # Not connected to the hardware\n\
uint32 OPENED = 1       # Passively connected to the hardware\n\
uint32 RUNNING = 2      # Sending hardware commands\n\
\n\
uint32 state\n\
\n\
";
  }

  static const char* value(const  ::art_msgs::SteeringState_<ContainerAllocator> &) { return value(); } 
};

template<class ContainerAllocator> struct HasHeader< ::art_msgs::SteeringState_<ContainerAllocator> > : public TrueType {};
template<class ContainerAllocator> struct HasHeader< const ::art_msgs::SteeringState_<ContainerAllocator> > : public TrueType {};
} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

template<class ContainerAllocator> struct Serializer< ::art_msgs::SteeringState_<ContainerAllocator> >
{
  template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
  {
    stream.next(m.header);
    stream.next(m.driver);
    stream.next(m.angle);
    stream.next(m.sensor);
  }

  ROS_DECLARE_ALLINONE_SERIALIZER;
}; // struct SteeringState_
} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::art_msgs::SteeringState_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const  ::art_msgs::SteeringState_<ContainerAllocator> & v) 
  {
    s << indent << "header: ";
s << std::endl;
    Printer< ::std_msgs::Header_<ContainerAllocator> >::stream(s, indent + "  ", v.header);
    s << indent << "driver: ";
s << std::endl;
    Printer< ::art_msgs::DriverState_<ContainerAllocator> >::stream(s, indent + "  ", v.driver);
    s << indent << "angle: ";
    Printer<float>::stream(s, indent + "  ", v.angle);
    s << indent << "sensor: ";
    Printer<float>::stream(s, indent + "  ", v.sensor);
  }
};


} // namespace message_operations
} // namespace ros

#endif // ART_MSGS_MESSAGE_STEERINGSTATE_H

