/* Auto-generated by genmsg_cpp for file /home/james/ros/art/utexas-art-ros-pkg-read-only/stacks/art_vehicle/art_msgs/msg/SteeringDiagnostics.msg */
#ifndef ART_MSGS_MESSAGE_STEERINGDIAGNOSTICS_H
#define ART_MSGS_MESSAGE_STEERINGDIAGNOSTICS_H
#include <string>
#include <vector>
#include <map>
#include <ostream>
#include "ros/serialization.h"
#include "ros/builtin_message_traits.h"
#include "ros/message_operations.h"
#include "ros/time.h"

#include "ros/macros.h"

#include "ros/assert.h"

#include "std_msgs/Header.h"

namespace art_msgs
{
template <class ContainerAllocator>
struct SteeringDiagnostics_ {
  typedef SteeringDiagnostics_<ContainerAllocator> Type;

  SteeringDiagnostics_()
  : header()
  , encoder(0)
  , last_request(0)
  , center_ticks(0)
  , status_word(0)
  {
  }

  SteeringDiagnostics_(const ContainerAllocator& _alloc)
  : header(_alloc)
  , encoder(0)
  , last_request(0)
  , center_ticks(0)
  , status_word(0)
  {
  }

  typedef  ::std_msgs::Header_<ContainerAllocator>  _header_type;
   ::std_msgs::Header_<ContainerAllocator>  header;

  typedef int32_t _encoder_type;
  int32_t encoder;

  typedef int32_t _last_request_type;
  int32_t last_request;

  typedef int32_t _center_ticks_type;
  int32_t center_ticks;

  typedef uint16_t _status_word_type;
  uint16_t status_word;


private:
  static const char* __s_getDataType_() { return "art_msgs/SteeringDiagnostics"; }
public:
  ROS_DEPRECATED static const std::string __s_getDataType() { return __s_getDataType_(); }

  ROS_DEPRECATED const std::string __getDataType() const { return __s_getDataType_(); }

private:
  static const char* __s_getMD5Sum_() { return "5dbe64bbef789e785f8333e897956d94"; }
public:
  ROS_DEPRECATED static const std::string __s_getMD5Sum() { return __s_getMD5Sum_(); }

  ROS_DEPRECATED const std::string __getMD5Sum() const { return __s_getMD5Sum_(); }

private:
  static const char* __s_getMessageDefinition_() { return "# ART steering controller diagnostics message\n\
\n\
# This message contains data not needed for normal operation of the\n\
# device, but useful for diagnosing problems with it.\n\
\n\
# $Id$\n\
\n\
Header  header\n\
\n\
int32 encoder                   # current reported encoder value\n\
int32 last_request              # last requested encoder value\n\
int32 center_ticks              # initial center encoder value\n\
uint16 status_word		# current internal status\n\
\n\
================================================================================\n\
MSG: std_msgs/Header\n\
# Standard metadata for higher-level stamped data types.\n\
# This is generally used to communicate timestamped data \n\
# in a particular coordinate frame.\n\
# \n\
# sequence ID: consecutively increasing ID \n\
uint32 seq\n\
#Two-integer timestamp that is expressed as:\n\
# * stamp.secs: seconds (stamp_secs) since epoch\n\
# * stamp.nsecs: nanoseconds since stamp_secs\n\
# time-handling sugar is provided by the client library\n\
time stamp\n\
#Frame this data is associated with\n\
# 0: no frame\n\
# 1: global frame\n\
string frame_id\n\
\n\
"; }
public:
  ROS_DEPRECATED static const std::string __s_getMessageDefinition() { return __s_getMessageDefinition_(); }

  ROS_DEPRECATED const std::string __getMessageDefinition() const { return __s_getMessageDefinition_(); }

  ROS_DEPRECATED virtual uint8_t *serialize(uint8_t *write_ptr, uint32_t seq) const
  {
    ros::serialization::OStream stream(write_ptr, 1000000000);
    ros::serialization::serialize(stream, header);
    ros::serialization::serialize(stream, encoder);
    ros::serialization::serialize(stream, last_request);
    ros::serialization::serialize(stream, center_ticks);
    ros::serialization::serialize(stream, status_word);
    return stream.getData();
  }

  ROS_DEPRECATED virtual uint8_t *deserialize(uint8_t *read_ptr)
  {
    ros::serialization::IStream stream(read_ptr, 1000000000);
    ros::serialization::deserialize(stream, header);
    ros::serialization::deserialize(stream, encoder);
    ros::serialization::deserialize(stream, last_request);
    ros::serialization::deserialize(stream, center_ticks);
    ros::serialization::deserialize(stream, status_word);
    return stream.getData();
  }

  ROS_DEPRECATED virtual uint32_t serializationLength() const
  {
    uint32_t size = 0;
    size += ros::serialization::serializationLength(header);
    size += ros::serialization::serializationLength(encoder);
    size += ros::serialization::serializationLength(last_request);
    size += ros::serialization::serializationLength(center_ticks);
    size += ros::serialization::serializationLength(status_word);
    return size;
  }

  typedef boost::shared_ptr< ::art_msgs::SteeringDiagnostics_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::art_msgs::SteeringDiagnostics_<ContainerAllocator>  const> ConstPtr;
  boost::shared_ptr<std::map<std::string, std::string> > __connection_header;
}; // struct SteeringDiagnostics
typedef  ::art_msgs::SteeringDiagnostics_<std::allocator<void> > SteeringDiagnostics;

typedef boost::shared_ptr< ::art_msgs::SteeringDiagnostics> SteeringDiagnosticsPtr;
typedef boost::shared_ptr< ::art_msgs::SteeringDiagnostics const> SteeringDiagnosticsConstPtr;


template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const  ::art_msgs::SteeringDiagnostics_<ContainerAllocator> & v)
{
  ros::message_operations::Printer< ::art_msgs::SteeringDiagnostics_<ContainerAllocator> >::stream(s, "", v);
  return s;}

} // namespace art_msgs

namespace ros
{
namespace message_traits
{
template<class ContainerAllocator> struct IsMessage< ::art_msgs::SteeringDiagnostics_<ContainerAllocator> > : public TrueType {};
template<class ContainerAllocator> struct IsMessage< ::art_msgs::SteeringDiagnostics_<ContainerAllocator>  const> : public TrueType {};
template<class ContainerAllocator>
struct MD5Sum< ::art_msgs::SteeringDiagnostics_<ContainerAllocator> > {
  static const char* value() 
  {
    return "5dbe64bbef789e785f8333e897956d94";
  }

  static const char* value(const  ::art_msgs::SteeringDiagnostics_<ContainerAllocator> &) { return value(); } 
  static const uint64_t static_value1 = 0x5dbe64bbef789e78ULL;
  static const uint64_t static_value2 = 0x5f8333e897956d94ULL;
};

template<class ContainerAllocator>
struct DataType< ::art_msgs::SteeringDiagnostics_<ContainerAllocator> > {
  static const char* value() 
  {
    return "art_msgs/SteeringDiagnostics";
  }

  static const char* value(const  ::art_msgs::SteeringDiagnostics_<ContainerAllocator> &) { return value(); } 
};

template<class ContainerAllocator>
struct Definition< ::art_msgs::SteeringDiagnostics_<ContainerAllocator> > {
  static const char* value() 
  {
    return "# ART steering controller diagnostics message\n\
\n\
# This message contains data not needed for normal operation of the\n\
# device, but useful for diagnosing problems with it.\n\
\n\
# $Id$\n\
\n\
Header  header\n\
\n\
int32 encoder                   # current reported encoder value\n\
int32 last_request              # last requested encoder value\n\
int32 center_ticks              # initial center encoder value\n\
uint16 status_word		# current internal status\n\
\n\
================================================================================\n\
MSG: std_msgs/Header\n\
# Standard metadata for higher-level stamped data types.\n\
# This is generally used to communicate timestamped data \n\
# in a particular coordinate frame.\n\
# \n\
# sequence ID: consecutively increasing ID \n\
uint32 seq\n\
#Two-integer timestamp that is expressed as:\n\
# * stamp.secs: seconds (stamp_secs) since epoch\n\
# * stamp.nsecs: nanoseconds since stamp_secs\n\
# time-handling sugar is provided by the client library\n\
time stamp\n\
#Frame this data is associated with\n\
# 0: no frame\n\
# 1: global frame\n\
string frame_id\n\
\n\
";
  }

  static const char* value(const  ::art_msgs::SteeringDiagnostics_<ContainerAllocator> &) { return value(); } 
};

template<class ContainerAllocator> struct HasHeader< ::art_msgs::SteeringDiagnostics_<ContainerAllocator> > : public TrueType {};
template<class ContainerAllocator> struct HasHeader< const ::art_msgs::SteeringDiagnostics_<ContainerAllocator> > : public TrueType {};
} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

template<class ContainerAllocator> struct Serializer< ::art_msgs::SteeringDiagnostics_<ContainerAllocator> >
{
  template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
  {
    stream.next(m.header);
    stream.next(m.encoder);
    stream.next(m.last_request);
    stream.next(m.center_ticks);
    stream.next(m.status_word);
  }

  ROS_DECLARE_ALLINONE_SERIALIZER;
}; // struct SteeringDiagnostics_
} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::art_msgs::SteeringDiagnostics_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const  ::art_msgs::SteeringDiagnostics_<ContainerAllocator> & v) 
  {
    s << indent << "header: ";
s << std::endl;
    Printer< ::std_msgs::Header_<ContainerAllocator> >::stream(s, indent + "  ", v.header);
    s << indent << "encoder: ";
    Printer<int32_t>::stream(s, indent + "  ", v.encoder);
    s << indent << "last_request: ";
    Printer<int32_t>::stream(s, indent + "  ", v.last_request);
    s << indent << "center_ticks: ";
    Printer<int32_t>::stream(s, indent + "  ", v.center_ticks);
    s << indent << "status_word: ";
    Printer<uint16_t>::stream(s, indent + "  ", v.status_word);
  }
};


} // namespace message_operations
} // namespace ros

#endif // ART_MSGS_MESSAGE_STEERINGDIAGNOSTICS_H

