(cl:in-package art_msgs-msg)
(cl:export '(LATITUDE-VAL
          LATITUDE
          LONGITUDE-VAL
          LONGITUDE
          MAPXY-VAL
          MAPXY
          ID-VAL
          ID
          INDEX-VAL
          INDEX
          IS_ENTRY-VAL
          IS_ENTRY
          IS_EXIT-VAL
          IS_EXIT
          IS_GOAL-VAL
          IS_GOAL
          IS_LANE_CHANGE-VAL
          IS_LANE_CHANGE
          IS_SPOT-VAL
          IS_SPOT
          IS_STOP-VAL
          IS_STOP
          IS_PERIMETER-VAL
          IS_PERIMETER
          CHECKPOINT_ID-VAL
          CHECKPOINT_ID
          LANE_WIDTH-VAL
          LANE_WIDTH
))