## *********************************************************
## 
## File autogenerated for the ackermann_qt package 
## by the dynamic_reconfigure package.
## Please do not edit.
## 
## ********************************************************/

##**********************************************************
## Software License Agreement (BSD License)
##
##  Copyright (c) 2008, Willow Garage, Inc.
##  All rights reserved.
##
##  Redistribution and use in source and binary forms, with or without
##  modification, are permitted provided that the following conditions
##  are met:
##
##   * Redistributions of source code must retain the above copyright
##     notice, this list of conditions and the following disclaimer.
##   * Redistributions in binary form must reproduce the above
##     copyright notice, this list of conditions and the following
##     disclaimer in the documentation and/or other materials provided
##     with the distribution.
##   * Neither the name of the Willow Garage nor the names of its
##     contributors may be used to endorse or promote products derived
##     from this software without specific prior written permission.
##
##  THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS
##  "AS IS" AND ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT
##  LIMITED TO, THE IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS
##  FOR A PARTICULAR PURPOSE ARE DISCLAIMED. IN NO EVENT SHALL THE
##  COPYRIGHT OWNER OR CONTRIBUTORS BE LIABLE FOR ANY DIRECT, INDIRECT,
##  INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL DAMAGES (INCLUDING,
##  BUT NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR SERVICES;
##  LOSS OF USE, DATA, OR PROFITS; OR BUSINESS INTERRUPTION) HOWEVER
##  CAUSED AND ON ANY THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT
##  LIABILITY, OR TORT (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN
##  ANY WAY OUT OF THE USE OF THIS SOFTWARE, EVEN IF ADVISED OF THE
##  POSSIBILITY OF SUCH DAMAGE.
##**********************************************************/

config_description = [{'srcline': 51, 'description': 'Smallest steering change recognized (radians).', 'max': 0.10000000000000001, 'cconsttype': 'const double', 'ctype': 'double', 'srcfile': '../cfg/QTeleop.cfg', 'name': 'epsilon_steering', 'edit_method': '', 'default': 1.7453292519943296e-05, 'level': 1, 'min': 0.0, 'type': 'double'}, {'srcline': 54, 'description': 'Maximum speed requested going forward (m/s).', 'max': 25.0, 'cconsttype': 'const double', 'ctype': 'double', 'srcfile': '../cfg/QTeleop.cfg', 'name': 'limit_forward', 'edit_method': '', 'default': 6.0, 'level': 1, 'min': 0.0, 'type': 'double'}, {'srcline': 57, 'description': 'Maximum speed requested in reverse (m/s).', 'max': 4.0, 'cconsttype': 'const double', 'ctype': 'double', 'srcfile': '../cfg/QTeleop.cfg', 'name': 'limit_reverse', 'edit_method': '', 'default': 3.0, 'level': 1, 'min': 0.0, 'type': 'double'}, {'srcline': 60, 'description': 'Maximum acceleration requested (m/s^2).', 'max': 25.0, 'cconsttype': 'const double', 'ctype': 'double', 'srcfile': '../cfg/QTeleop.cfg', 'name': 'max_accel', 'edit_method': '', 'default': 10.0, 'level': 1, 'min': 0.0, 'type': 'double'}, {'srcline': 63, 'description': 'Maximum (left) steering limit (radians).', 'max': 1.5707963267948966, 'cconsttype': 'const double', 'ctype': 'double', 'srcfile': '../cfg/QTeleop.cfg', 'name': 'max_steering', 'edit_method': '', 'default': 0.50614548307835561, 'level': 1, 'min': 0.10000000000000001, 'type': 'double'}, {'srcline': 66, 'description': 'Minimum (right) steering limit (radians).', 'max': -0.10000000000000001, 'cconsttype': 'const double', 'ctype': 'double', 'srcfile': '../cfg/QTeleop.cfg', 'name': 'min_steering', 'edit_method': '', 'default': -0.50614548307835561, 'level': 1, 'min': -1.5707963267948966, 'type': 'double'}]

min = {}
max = {}
defaults = {}
level = {}
type = {}
all_level = 0

for param in config_description:
    min[param['name']] = param['min']
    max[param['name']] = param['max']
    defaults[param['name']] = param['default']
    level[param['name']] = param['level']
    type[param['name']] = param['type']
    all_level = all_level | param['level']

