/* Auto-generated by genmsg_cpp for file /home/james/ros/controller/my_controller_pkg/srv/SetAmplitude.srv */
#ifndef MY_CONTROLLER_PKG_SERVICE_SETAMPLITUDE_H
#define MY_CONTROLLER_PKG_SERVICE_SETAMPLITUDE_H
#include <string>
#include <vector>
#include <map>
#include <ostream>
#include "ros/serialization.h"
#include "ros/builtin_message_traits.h"
#include "ros/message_operations.h"
#include "ros/time.h"

#include "ros/macros.h"

#include "ros/assert.h"

#include "ros/service_traits.h"




namespace my_controller_pkg
{
template <class ContainerAllocator>
struct SetAmplitudeRequest_ {
  typedef SetAmplitudeRequest_<ContainerAllocator> Type;

  SetAmplitudeRequest_()
  : amplitude(0.0)
  {
  }

  SetAmplitudeRequest_(const ContainerAllocator& _alloc)
  : amplitude(0.0)
  {
  }

  typedef double _amplitude_type;
  double amplitude;


private:
  static const char* __s_getDataType_() { return "my_controller_pkg/SetAmplitudeRequest"; }
public:
  ROS_DEPRECATED static const std::string __s_getDataType() { return __s_getDataType_(); }

  ROS_DEPRECATED const std::string __getDataType() const { return __s_getDataType_(); }

private:
  static const char* __s_getMD5Sum_() { return "0eeaf0bd32ede16f811b8cce1a39fcc0"; }
public:
  ROS_DEPRECATED static const std::string __s_getMD5Sum() { return __s_getMD5Sum_(); }

  ROS_DEPRECATED const std::string __getMD5Sum() const { return __s_getMD5Sum_(); }

private:
  static const char* __s_getServerMD5Sum_() { return "e68e53e50ad5dca32bcdd4bd08619ffb"; }
public:
  ROS_DEPRECATED static const std::string __s_getServerMD5Sum() { return __s_getServerMD5Sum_(); }

  ROS_DEPRECATED const std::string __getServerMD5Sum() const { return __s_getServerMD5Sum_(); }

private:
  static const char* __s_getMessageDefinition_() { return "float64 amplitude\n\
\n\
"; }
public:
  ROS_DEPRECATED static const std::string __s_getMessageDefinition() { return __s_getMessageDefinition_(); }

  ROS_DEPRECATED const std::string __getMessageDefinition() const { return __s_getMessageDefinition_(); }

  ROS_DEPRECATED virtual uint8_t *serialize(uint8_t *write_ptr, uint32_t seq) const
  {
    ros::serialization::OStream stream(write_ptr, 1000000000);
    ros::serialization::serialize(stream, amplitude);
    return stream.getData();
  }

  ROS_DEPRECATED virtual uint8_t *deserialize(uint8_t *read_ptr)
  {
    ros::serialization::IStream stream(read_ptr, 1000000000);
    ros::serialization::deserialize(stream, amplitude);
    return stream.getData();
  }

  ROS_DEPRECATED virtual uint32_t serializationLength() const
  {
    uint32_t size = 0;
    size += ros::serialization::serializationLength(amplitude);
    return size;
  }

  typedef boost::shared_ptr< ::my_controller_pkg::SetAmplitudeRequest_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::my_controller_pkg::SetAmplitudeRequest_<ContainerAllocator>  const> ConstPtr;
  boost::shared_ptr<std::map<std::string, std::string> > __connection_header;
}; // struct SetAmplitudeRequest
typedef  ::my_controller_pkg::SetAmplitudeRequest_<std::allocator<void> > SetAmplitudeRequest;

typedef boost::shared_ptr< ::my_controller_pkg::SetAmplitudeRequest> SetAmplitudeRequestPtr;
typedef boost::shared_ptr< ::my_controller_pkg::SetAmplitudeRequest const> SetAmplitudeRequestConstPtr;


template <class ContainerAllocator>
struct SetAmplitudeResponse_ {
  typedef SetAmplitudeResponse_<ContainerAllocator> Type;

  SetAmplitudeResponse_()
  : amplitude(0.0)
  {
  }

  SetAmplitudeResponse_(const ContainerAllocator& _alloc)
  : amplitude(0.0)
  {
  }

  typedef double _amplitude_type;
  double amplitude;


private:
  static const char* __s_getDataType_() { return "my_controller_pkg/SetAmplitudeResponse"; }
public:
  ROS_DEPRECATED static const std::string __s_getDataType() { return __s_getDataType_(); }

  ROS_DEPRECATED const std::string __getDataType() const { return __s_getDataType_(); }

private:
  static const char* __s_getMD5Sum_() { return "0eeaf0bd32ede16f811b8cce1a39fcc0"; }
public:
  ROS_DEPRECATED static const std::string __s_getMD5Sum() { return __s_getMD5Sum_(); }

  ROS_DEPRECATED const std::string __getMD5Sum() const { return __s_getMD5Sum_(); }

private:
  static const char* __s_getServerMD5Sum_() { return "e68e53e50ad5dca32bcdd4bd08619ffb"; }
public:
  ROS_DEPRECATED static const std::string __s_getServerMD5Sum() { return __s_getServerMD5Sum_(); }

  ROS_DEPRECATED const std::string __getServerMD5Sum() const { return __s_getServerMD5Sum_(); }

private:
  static const char* __s_getMessageDefinition_() { return "float64 amplitude\n\
\n\
\n\
"; }
public:
  ROS_DEPRECATED static const std::string __s_getMessageDefinition() { return __s_getMessageDefinition_(); }

  ROS_DEPRECATED const std::string __getMessageDefinition() const { return __s_getMessageDefinition_(); }

  ROS_DEPRECATED virtual uint8_t *serialize(uint8_t *write_ptr, uint32_t seq) const
  {
    ros::serialization::OStream stream(write_ptr, 1000000000);
    ros::serialization::serialize(stream, amplitude);
    return stream.getData();
  }

  ROS_DEPRECATED virtual uint8_t *deserialize(uint8_t *read_ptr)
  {
    ros::serialization::IStream stream(read_ptr, 1000000000);
    ros::serialization::deserialize(stream, amplitude);
    return stream.getData();
  }

  ROS_DEPRECATED virtual uint32_t serializationLength() const
  {
    uint32_t size = 0;
    size += ros::serialization::serializationLength(amplitude);
    return size;
  }

  typedef boost::shared_ptr< ::my_controller_pkg::SetAmplitudeResponse_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::my_controller_pkg::SetAmplitudeResponse_<ContainerAllocator>  const> ConstPtr;
  boost::shared_ptr<std::map<std::string, std::string> > __connection_header;
}; // struct SetAmplitudeResponse
typedef  ::my_controller_pkg::SetAmplitudeResponse_<std::allocator<void> > SetAmplitudeResponse;

typedef boost::shared_ptr< ::my_controller_pkg::SetAmplitudeResponse> SetAmplitudeResponsePtr;
typedef boost::shared_ptr< ::my_controller_pkg::SetAmplitudeResponse const> SetAmplitudeResponseConstPtr;

struct SetAmplitude
{

typedef SetAmplitudeRequest Request;
typedef SetAmplitudeResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;
}; // struct SetAmplitude
} // namespace my_controller_pkg

namespace ros
{
namespace message_traits
{
template<class ContainerAllocator> struct IsMessage< ::my_controller_pkg::SetAmplitudeRequest_<ContainerAllocator> > : public TrueType {};
template<class ContainerAllocator> struct IsMessage< ::my_controller_pkg::SetAmplitudeRequest_<ContainerAllocator>  const> : public TrueType {};
template<class ContainerAllocator>
struct MD5Sum< ::my_controller_pkg::SetAmplitudeRequest_<ContainerAllocator> > {
  static const char* value() 
  {
    return "0eeaf0bd32ede16f811b8cce1a39fcc0";
  }

  static const char* value(const  ::my_controller_pkg::SetAmplitudeRequest_<ContainerAllocator> &) { return value(); } 
  static const uint64_t static_value1 = 0x0eeaf0bd32ede16fULL;
  static const uint64_t static_value2 = 0x811b8cce1a39fcc0ULL;
};

template<class ContainerAllocator>
struct DataType< ::my_controller_pkg::SetAmplitudeRequest_<ContainerAllocator> > {
  static const char* value() 
  {
    return "my_controller_pkg/SetAmplitudeRequest";
  }

  static const char* value(const  ::my_controller_pkg::SetAmplitudeRequest_<ContainerAllocator> &) { return value(); } 
};

template<class ContainerAllocator>
struct Definition< ::my_controller_pkg::SetAmplitudeRequest_<ContainerAllocator> > {
  static const char* value() 
  {
    return "float64 amplitude\n\
\n\
";
  }

  static const char* value(const  ::my_controller_pkg::SetAmplitudeRequest_<ContainerAllocator> &) { return value(); } 
};

template<class ContainerAllocator> struct IsFixedSize< ::my_controller_pkg::SetAmplitudeRequest_<ContainerAllocator> > : public TrueType {};
} // namespace message_traits
} // namespace ros


namespace ros
{
namespace message_traits
{
template<class ContainerAllocator> struct IsMessage< ::my_controller_pkg::SetAmplitudeResponse_<ContainerAllocator> > : public TrueType {};
template<class ContainerAllocator> struct IsMessage< ::my_controller_pkg::SetAmplitudeResponse_<ContainerAllocator>  const> : public TrueType {};
template<class ContainerAllocator>
struct MD5Sum< ::my_controller_pkg::SetAmplitudeResponse_<ContainerAllocator> > {
  static const char* value() 
  {
    return "0eeaf0bd32ede16f811b8cce1a39fcc0";
  }

  static const char* value(const  ::my_controller_pkg::SetAmplitudeResponse_<ContainerAllocator> &) { return value(); } 
  static const uint64_t static_value1 = 0x0eeaf0bd32ede16fULL;
  static const uint64_t static_value2 = 0x811b8cce1a39fcc0ULL;
};

template<class ContainerAllocator>
struct DataType< ::my_controller_pkg::SetAmplitudeResponse_<ContainerAllocator> > {
  static const char* value() 
  {
    return "my_controller_pkg/SetAmplitudeResponse";
  }

  static const char* value(const  ::my_controller_pkg::SetAmplitudeResponse_<ContainerAllocator> &) { return value(); } 
};

template<class ContainerAllocator>
struct Definition< ::my_controller_pkg::SetAmplitudeResponse_<ContainerAllocator> > {
  static const char* value() 
  {
    return "float64 amplitude\n\
\n\
\n\
";
  }

  static const char* value(const  ::my_controller_pkg::SetAmplitudeResponse_<ContainerAllocator> &) { return value(); } 
};

template<class ContainerAllocator> struct IsFixedSize< ::my_controller_pkg::SetAmplitudeResponse_<ContainerAllocator> > : public TrueType {};
} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

template<class ContainerAllocator> struct Serializer< ::my_controller_pkg::SetAmplitudeRequest_<ContainerAllocator> >
{
  template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
  {
    stream.next(m.amplitude);
  }

  ROS_DECLARE_ALLINONE_SERIALIZER;
}; // struct SetAmplitudeRequest_
} // namespace serialization
} // namespace ros


namespace ros
{
namespace serialization
{

template<class ContainerAllocator> struct Serializer< ::my_controller_pkg::SetAmplitudeResponse_<ContainerAllocator> >
{
  template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
  {
    stream.next(m.amplitude);
  }

  ROS_DECLARE_ALLINONE_SERIALIZER;
}; // struct SetAmplitudeResponse_
} // namespace serialization
} // namespace ros

namespace ros
{
namespace service_traits
{
template<>
struct MD5Sum<my_controller_pkg::SetAmplitude> {
  static const char* value() 
  {
    return "e68e53e50ad5dca32bcdd4bd08619ffb";
  }

  static const char* value(const my_controller_pkg::SetAmplitude&) { return value(); } 
};

template<>
struct DataType<my_controller_pkg::SetAmplitude> {
  static const char* value() 
  {
    return "my_controller_pkg/SetAmplitude";
  }

  static const char* value(const my_controller_pkg::SetAmplitude&) { return value(); } 
};

template<class ContainerAllocator>
struct MD5Sum<my_controller_pkg::SetAmplitudeRequest_<ContainerAllocator> > {
  static const char* value() 
  {
    return "e68e53e50ad5dca32bcdd4bd08619ffb";
  }

  static const char* value(const my_controller_pkg::SetAmplitudeRequest_<ContainerAllocator> &) { return value(); } 
};

template<class ContainerAllocator>
struct DataType<my_controller_pkg::SetAmplitudeRequest_<ContainerAllocator> > {
  static const char* value() 
  {
    return "my_controller_pkg/SetAmplitude";
  }

  static const char* value(const my_controller_pkg::SetAmplitudeRequest_<ContainerAllocator> &) { return value(); } 
};

template<class ContainerAllocator>
struct MD5Sum<my_controller_pkg::SetAmplitudeResponse_<ContainerAllocator> > {
  static const char* value() 
  {
    return "e68e53e50ad5dca32bcdd4bd08619ffb";
  }

  static const char* value(const my_controller_pkg::SetAmplitudeResponse_<ContainerAllocator> &) { return value(); } 
};

template<class ContainerAllocator>
struct DataType<my_controller_pkg::SetAmplitudeResponse_<ContainerAllocator> > {
  static const char* value() 
  {
    return "my_controller_pkg/SetAmplitude";
  }

  static const char* value(const my_controller_pkg::SetAmplitudeResponse_<ContainerAllocator> &) { return value(); } 
};

} // namespace service_traits
} // namespace ros

#endif // MY_CONTROLLER_PKG_SERVICE_SETAMPLITUDE_H

